name: "Webex Notification"
description: "Sends a Webex notification"
inputs:
  webexToken:
    description: "Webex authentication token"
    required: true
  roomID:
    description: "Webex Room ID where the message will be sent"
    required: true
  textMsg:
    description: "The message, in plain text. If markdown is specified this parameter may be optionally used to provide alternate text for UI clients that do not support rich text. The maximum message length is 7439 bytes."
    required: false
    default: ""
  markdownMsg:
    description: "The message, in Markdown format. The maximum message length is 7439 bytes."
    required: false
    default: ""
outputs:
  msgId:
    description: "The unique identifier for the message."
runs:
  using: "docker"
  image: "docker://adealdag/action-webex-notification:v1.0"
